version: "3.8"

services:
  # 用户API服务
  user-api:
    build:
      context: ../../
      dockerfile: deploy/dev/Dockerfile
      target: api-service
    container_name: miniblog-user-api
    ports:
      - "8888:8888"
    volumes:
      - ../../:/app
      - go-cache:/go/pkg/mod
      - air-cache:/root/.cache/go-build
      - ../../logs:/var/log/app # 整个日志目录挂载（让应用可以访问所有日志目录）
    environment:
      - SERVICE_NAME=user-api
      - SERVICE_PATH=./apps/user/api
      - CONFIG_FILE=./apps/user/api/etc/user.yaml
    networks:
      - miniblog-network
    depends_on:
      - user-rpc
    command: ["air", "-c", "/app/deploy/dev/air/user-api.toml"]

  # 用户RPC服务
  user-rpc:
    build:
      context: ../../
      dockerfile: deploy/dev/Dockerfile
      target: rpc-service
    container_name: miniblog-user-rpc
    ports:
      - "8889:8889"
    volumes:
      - ../../:/app
      - go-cache:/go/pkg/mod
      - air-cache:/root/.cache/go-build
      - ../../logs:/var/log/app # 整个日志目录挂载（让应用可以访问所有日志目录）
    environment:
      - SERVICE_NAME=user-rpc
      - SERVICE_PATH=./apps/user/rpc
      - CONFIG_FILE=./apps/user/rpc/etc/user.yaml
    networks:
      - miniblog-network
    command: ["air", "-c", "/app/deploy/dev/air/user-rpc.toml"]

  # Nginx网关
  nginx:
    image: nginx:alpine
    container_name: miniblog-nginx
    ports:
      - "8099:8099"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../../logs/nginx:/var/log/nginx # nginx 日志目录挂载
      - ../../logs:/var/log/app # 整个日志目录（用于访问其他服务日志）
    networks:
      - miniblog-network
    depends_on:
      - user-api
      - user-rpc
    restart: unless-stopped

networks:
  miniblog-network:
    external: true
    name: miniblog-network

volumes:
  go-cache:
  air-cache:
