# Copyright 2025 长林啊 &lt;767425412@qq.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/clin211/miniblog-v3.git.

basePath: /
consumes:
- application/json
info:
  description: 用户 api 生成 swagger...
  title: 用户 API
  version: v1
paths:
  /user/{userId}:
    delete:
      consumes:
      - application/json
      operationId: deleteUser
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            userId:
              description: 用户ID
              type: string
          required:
          - userId
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              success:
                description: 是否成功
                type: boolean
            type: object
      schemes:
      - https
      summary: DeleteUser
    get:
      operationId: getUser
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            userId:
              description: 用户ID
              type: string
          required:
          - userId
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              age:
                description: 年龄
                type: integer
              avatar:
                description: 头像URL
                type: string
              createdAt:
                description: 创建时间
                type: string
              email:
                description: 邮箱
                type: string
              gender:
                description: 性别
                type: integer
              phone:
                description: 手机号
                type: string
              status:
                description: 状态
                type: integer
              updatedAt:
                description: 更新时间
                type: string
              userId:
                description: 用户ID
                type: string
              username:
                description: 用户名
                type: string
            type: object
      schemes:
      - https
      summary: GetUser
    put:
      consumes:
      - application/json
      operationId: updateUser
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            age:
              description: 年龄
              type: integer
            avatar:
              description: 头像URL
              type: string
            gender:
              description: 性别
              type: integer
            userId:
              description: 用户ID
              type: string
            username:
              description: 用户名
              type: string
          required:
          - userId
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              updatedAt:
                description: 更新时间
                type: string
              userId:
                description: 用户ID
                type: string
              username:
                description: 用户名
                type: string
            type: object
      schemes:
      - https
      summary: UpdateUser
  /user/login:
    post:
      consumes:
      - application/json
      operationId: login
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            password:
              description: 密码
              type: string
            username:
              description: 用户名/邮箱/手机号
              type: string
          required:
          - username
          - password
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              expireAt:
                description: 过期时间
                type: string
              token:
                description: JWT Token
                type: string
            type: object
      schemes:
      - https
      summary: Login
  /user/register:
    post:
      consumes:
      - application/json
      operationId: register
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            age:
              description: 年龄
              type: integer
            avatar:
              description: 头像URL
              type: string
            email:
              description: 邮箱
              type: string
            gender:
              description: 性别：0-未设置，1-男，2-女，3-其他
              type: integer
            password:
              description: 密码
              type: string
            phone:
              description: 手机号
              type: string
            registerSource:
              description: 注册来源：1-web，2-app，3-wechat，4-qq，5-github，6-google
              type: integer
            username:
              description: 用户名
              type: string
          required:
          - username
          - password
          - email
          - phone
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              userId:
                description: 用户ID
                type: string
            type: object
      schemes:
      - https
      summary: Register
produces:
- application/json
schemes:
- https
swagger: "2.0"
x-date: "2025-08-22 09:22:01"
x-description: This is a goctl generated swagger file.
x-github: https://github.com/zeromicro/go-zero
x-go-zero-doc: https://go-zero.dev/
x-goctl-version: 1.8.4
