name: Release CI/CD Pipeline

on:
  push:
    branches:
      - release
  workflow_dispatch:
    inputs:
      environment:
        description: '部署环境'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  # 本地构建的镜像标签
  IMAGE_TAG: release

jobs:
  # 代码质量检查
  code-quality:
    name: 代码质量检查
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Go 环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          cache: true

      - name: 运行代码检查
        run: |
          echo "运行 go mod tidy..."
          go mod tidy

          echo "运行 go vet..."
          go vet ./...

          echo "运行 go fmt 检查..."
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "代码格式不正确，请运行 go fmt ./..."
            gofmt -s -l .
            exit 1
          fi

          echo "代码质量检查通过"

  # 构建 Docker 镜像
  build:
    name: 构建镜像
    needs: code-quality
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 构建 user-api 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/prod/Dockerfile.user-api
          push: false
          load: true
          tags: miniblog-user-api:release
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 构建 user-rpc 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/prod/Dockerfile.user-rpc
          push: false
          load: true
          tags: miniblog-user-rpc:release
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 保存镜像为 tar 文件
        run: |
          docker save miniblog-user-api:release -o miniblog-user-api.tar
          docker save miniblog-user-rpc:release -o miniblog-user-rpc.tar

      - name: 上传镜像为 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            miniblog-user-api.tar
            miniblog-user-rpc.tar
          retention-days: 1

      - name: 输出镜像信息
        run: |
          echo "User API 镜像: miniblog-user-api:release"
          echo "User RPC 镜像: miniblog-user-rpc:release"
          ls -la *.tar

  # 部署到服务器
  deploy:
    name: 部署到服务器
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 下载构建的镜像
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: ./images

      - name: 上传部署文件
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy/prod/*"
          target: "/home/project/miniblog-v3/"
          strip_components: 1

      - name: 上传 Docker 镜像
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "images/*.tar"
          target: "/home/project/miniblog-v3/"

      - name: 创建部署目录结构
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/project/miniblog-v3/logs
            mkdir -p /home/project/miniblog-v3/nginx

      - name: 设置文件权限
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/project/miniblog-v3
            chmod +x deploy.sh
            chmod +x infrastructure-manager.sh
            chmod +x kafka-manager.sh
            chmod +x nginx-manager.sh
            chmod +x nginx/conf.d/service-manager.sh

      - name: 更新环境变量
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/project/miniblog-v3
            # 设置镜像标签为 release
            echo "IMAGE_TAG=release" > .env
            echo "# 本地构建的镜像配置" >> .env
            echo "# 镜像已通过 docker load 加载到本地" >> .env

      - name: 加载 Docker 镜像
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/project/miniblog-v3
            docker load -i miniblog-user-api.tar
            docker load -i miniblog-user-rpc.tar
            docker images | grep miniblog

      - name: 启动基础设施服务
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/project/miniblog-v3
            ./infrastructure-manager.sh start

      - name: 等待基础设施服务就绪
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "等待 MySQL 服务就绪..."
            timeout 60 bash -c 'until docker exec miniblog-v3-mysql-1 mysqladmin ping -h"localhost" --silent; do sleep 2; done'

            echo "等待 Redis 服务就绪..."
            timeout 30 bash -c 'until docker exec miniblog-v3-redis-1 redis-cli ping; do sleep 2; done'

            echo "等待 etcd 服务就绪..."
            timeout 30 bash -c 'until docker exec miniblog-v3-etcd-1 etcdctl endpoint health; do sleep 2; done'

      - name: 启动应用服务
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/project/miniblog-v3
            docker-compose up -d user-api user-rpc

      - name: 等待应用服务启动
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "等待应用服务启动..."
            sleep 30

      - name: 验证部署
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/project/miniblog-v3

            echo "检查服务状态..."
            docker-compose ps

            echo "执行健康检查..."
            if curl -f http://localhost:8888/health; then
              echo "✅ User API 健康检查通过"
            else
              echo "❌ User API 健康检查失败"
              exit 1
            fi

            if curl -f http://localhost:8080/health; then
              echo "✅ User RPC 健康检查通过"
            else
              echo "❌ User RPC 健康检查失败"
              exit 1
            fi

      - name: 清理临时文件
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/project/miniblog-v3
            rm -f *.tar

  # 通知部署结果
  notify:
    name: 部署通知
    needs: [deploy]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: 部署成功通知
        if: needs.deploy.result == 'success'
        run: |
          echo "✅ 部署成功！"
          echo "服务地址: http://${{ secrets.SERVER_HOST }}"
          echo "User API: http://${{ secrets.SERVER_HOST }}:8888"
          echo "User RPC: http://${{ secrets.SERVER_HOST }}:8080"
          echo ""
          echo "基础设施服务："
          echo "  - MySQL: ${{ secrets.SERVER_HOST }}:3306"
          echo "  - Redis: ${{ secrets.SERVER_HOST }}:6379"
          echo "  - etcd: ${{ secrets.SERVER_HOST }}:2379"
          echo "  - Kafka: ${{ secrets.SERVER_HOST }}:29092"
          echo ""
          echo "下一步操作："
          echo "  1. 配置外部 nginx: ./nginx-manager.sh install"
          echo "  2. 创建 Kafka 主题: ./kafka-manager.sh create-default"
          echo "  3. 检查服务状态: ./infrastructure-manager.sh status"

      - name: 部署失败通知
        if: needs.deploy.result == 'failure'
        run: |
          echo "❌ 部署失败！"
          echo "请检查部署日志以获取详细信息"
